---
dependencies:
  - role: tersmitten.postfix
    postfix_aliases:
      - { user: root, alias: "{{ admin_email }}" }
    postfix_inet_interfaces: '127.0.0.1, [::1], 172.18.0.1'
    postfix_mynetworks:
      - '127.0.0.0/8'
      - '[::ffff:127.0.0.0]/104'
      - '[::1]/128'
      - '172.18.0.0/16'
    postfix_sasl_password: "{{ _postfix.sasl_password }}"
  - role: jnv.unattended-upgrades
    unattended_mail: root
    unattended_mail_only_on_error: yes
    unattended_remove_unused_dependencies: yes
    unattended_ignore_apps_require_restart: yes
