---
- apt: name={{ item }}
  with_items:
    - ruby-bundler

- mysql_db:
    name: "{{ db_name }}"

- mysql_user:
    name: "{{ db_name }}"
    password: "{{ _mysql.passwords[db_name] }}"
    priv: "{{ db_name }}.*:ALL"
    host: "{{ php_ip }}"

- lineinfile: dest=/etc/mysql/backup.txt line={{ db_name }}

- file:
    path: "{{ caddy_root }}/{{ item }}"
    state: directory
    mode: "a+rX"
    owner: www-data
    group: www-data
    recurse: yes
  with_items:
    - wordpress
    - logs

- copy: src=php.ini dest={{ caddy_root }}/php.ini
  notify: restart {{ sitename }}

- template:
    src: Caddyfile.j2
    dest: "{{ caddy_root }}/Caddyfile"
    validate: /usr/local/bin/caddy -conf %s -validate
  notify: reload caddy

- file:
    src: "{{ caddy_root }}/Caddyfile"
    dest: /etc/caddy/vhosts/{{ sitename }}.conf
    state: link

- template: dest=/etc/systemd/system/wordpress-{{ sitename }}.service src=wordpress.service.j2
  notify:
    - reload systemd
    - restart {{ sitename }}

- meta: flush_handlers

- service: name=wordpress-{{ sitename }} state=started enabled=yes
