---
- mysql_db:
    name: "{{ db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci

- mysql_user:
    name: "{{ db_name }}"
    password: "{{ _mysql.passwords[db_name] }}"
    priv: "{{ db_name }}.*:ALL"
    host: "{{ php_ip }}"

- lineinfile: dest=/etc/mysql/backup.txt line={{ db_name }}

- file:
    path: "{{ caddy_root }}/{{ item }}"
    state: directory
    mode: "a+rX"
    owner: www-data
    group: www-data
    recurse: yes
  with_items:
    - wordpress
    - logs

- copy: src=php.ini dest={{ caddy_root }}/php.ini

- docker_container:
    name: wordpress-{{ sitename }}
    dns_search_domains:
      - oobak.net
    volumes:
      - "{{ caddy_root }}/php.ini:/usr/local/etc/php/php.ini:ro"
      - "{{ caddy_root }}/wordpress:/var/www/html"
    networks:
      - name: bridge-static
        ipv4_address: "{{ php_ip }}"
    image: wordpress:{{ docker_image }}
    working_dir: /var/www/html{{ php_htdocs }}{{ wp_siteurl }}
    command: -- php-fpm
    restart_policy: unless-stopped

- template:
    src: Caddyfile.j2
    dest: "{{ caddy_root }}/Caddyfile"
    validate: /usr/local/bin/caddy -conf %s -validate
  notify: reload caddy

- file:
    src: "{{ caddy_root }}/Caddyfile"
    dest: /etc/caddy/vhosts/{{ sitename }}.conf
    state: link
  notify: reload caddy
