---
dependencies:
  - common
  - www-data
  - goaccess
  - role: antoiner77.caddy
    caddy_features: http.ipfilter,http.filter,http.ratelimit,http.git
    caddy_config: |
      import vhosts/*.conf

      localhost:8080 {
        tls off
        root /var/www/phpMyAdmin
        fastcgi / localhost:9000 php
      }
