---
- apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: '0xF1656F24C74CD1D8'

- apt_repository:
    repo: deb [arch=amd64,i386] http://mirror.jaleco.com/mariadb/repo/10.1/ubuntu {{ ansible_distribution_release }} main
    filename: mariadb
    state: absent
    update_cache: yes

- apt_repository:
    repo: deb [arch=amd64,i386] http://mirror.jaleco.com/mariadb/repo/10.2/ubuntu {{ ansible_distribution_release }} main
    filename: mariadb
    update_cache: yes

- apt:
    name:
      - mariadb-server
      - python-mysqldb
      - python-pexpect

- stat: path=/var/lib/mysql/installation_secured
  register: installation_secured

- include: mysql_secure_installation.yml
  when: installation_secured.stat.islnk is not defined

- file: path=/var/lib/mysql/installation_secured state=touch
  when: installation_secured.stat.islnk is not defined

- template: dest=/root/.my.cnf src=my.cnf.j2 mode=0600

- template: dest=/etc/mysql/conf.d/wordpress.cnf src=wordpress.cnf.j2
  notify: restart mariadb

- service: name=mariadb state=started enabled=yes

- copy: content= dest=/etc/mysql/backup.txt force=no

- copy: content= dest=/etc/mysql/snapshot.txt force=no

- file: path=/var/backups/mysql state=directory mode=0750 owner=root group=users

- copy: src=backup_mysql.sh dest=/etc/cron.daily/backup-mysql mode=0700 owner=root group=root
