---
- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    update_cache: yes

- apt:
    name:
      - docker-ce
      - python3-docker
  register: packages

- service: name=docker state=started enabled=yes

- docker_container:
    name: watchtower
    env:
      WATCHTOWER_NOTIFICATIONS_LEVEL: warn
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: 172.17.0.1
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY: "true"
    dns_search_domains:
      - oobak.net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    image: v2tec/watchtower
    command: --cleanup
    restart_policy: unless-stopped

- include_vars: file={{ lookup('env', 'PWD') }}/users.yml

- user:
    name: "{{ item.name }}"
    groups: docker
    append: yes
  loop: "{{ users }}"

- docker_network:
    name: bridge-static
    driver_options:
      com.docker.network.bridge.name: docker1
    ipam_options:
      subnet: 172.18.0.0/16

- file: dest=/etc/systemd/system/postfix@-.service.d state=directory

- ini_file:
    path: /etc/systemd/system/postfix@-.service.d/override.conf
    section: Unit
    option: After
    value: docker.service
    no_extra_spaces: yes
  notify:
    - reload systemd

- ufw: rule=limit direction=in if=docker1 name=Postfix
