---
- file:
    path: "{{ caddy_root }}/{{ item }}"
    state: directory
    mode: "a+rX"
    owner: www-data
    group: www-data
    recurse: yes
  with_items:
    - html
    - logs

- copy: src=php.ini dest={{ caddy_root }}/php.ini

- docker_container:
    name: php-{{ sitename }}
    dns_search_domains:
      - oobak.net
    volumes:
      - "{{ caddy_root }}/php.ini:/usr/local/etc/php/php.ini:ro"
      - "{{ caddy_root }}/html:/var/www/html"
    networks:
      - name: bridge-static
        ipv4_address: "{{ php_ip }}"
    image: php:{{ docker_image }}
    restart_policy: unless-stopped

- template:
    src: Caddyfile.j2
    dest: "{{ caddy_root }}/Caddyfile"
    validate: /usr/local/bin/caddy -conf %s -validate
  notify: reload caddy

- file:
    src: "{{ caddy_root }}/Caddyfile"
    dest: /etc/caddy/vhosts/{{ sitename }}.conf
    state: link
  notify: reload caddy
